### ISSUE TITLE
Record that was APISO valid when imported becomes invalid in GeoNetwork

### ISSUE THREAD

**Issue by nmtoken** [metadata101/iso19139.gemini23#4]
Looking at my record with file identifier `<gco:CharacterString>ea819b92-d389-193a-e044-002128a47908</gco:CharacterString>`   which is `BGSsv-examplea1.xml` at https://github.com/AGIGemini/Schematron/tree/master/samples

If I validate this file using the APISO schema in oXygen I'm told it's valid.

If I look at the same file that has been imported into the geonet38 server (and then harvested by me) and validate that file using the APISO schema in oXygen I'm told it's not-valid.

In the original file I have:

`<gmd:verticalElement gco:nilReason="inapplicable"/>`

In the geonet38  version of the file this has been changed to:

    <gmd:verticalElement gco:nilReason="missing">
        <gco:CharacterString/>
    </gmd:verticalElement>`

Causing the validation fail:

**Invalid content was found starting with element '{"http://www.isotc211.org/2005/gco":CharacterString}'. One of '{"http://www.isotc211.org/2005/gmd":EX_VerticalExtent}' is expected.**

**Comment by archaeogeek** [comment]
Closing as discussion is in https://github.com/metadata101/iso19139.gemini23/issues/5
