### ISSUE TITLE
Imported Metadata records have nil reason changed 

### ISSUE THREAD

**Issue by nmtoken** [metadata101/iso19139.gemini23#6]
As mentioned in #4 and #5

valid metadata records that use nil reason of **inapplicable** have value changed to **missing**, changing the semantics of the metadata

Original value should be preserved

**Comment by archaeogeek** [comment]
Working on this one- unfortunately there's no clear guidance (I did a search through the entire AGI guidance) as to which elements are allowed to have a nil reason of inapplicable so we're having to address each one as we come across it.

**Comment by nmtoken** [comment]
But fundamentally the metadata shouldn't change.  It isn't a case of what's allowed per se, it's about what was in the input metadata.    A change should only occur on some validation step, and only on a prompt where the value is invalid, but in this example no validation has (or should have occurred), and no prompt was given.

**Comment by archaeogeek** [comment]
The background question is how to display elements with a nilreason other than missing in the editor interface. The Geonetwork developers have suggested a work around that involves changing the display of the element **purely while it's in edit mode** but then reverting back to what it was when the record is saved or validated. What you've picked up here is another element that we need to add to the reversion code. Like I said, it's a work in progress...

**Comment by archaeogeek** [comment]
Closing as discussion is in https://github.com/metadata101/iso19139.gemini23/issues/5
