### ISSUE TITLE
Series metadata example fails MI-41a and MI41o

### ISSUE THREAD

**Issue by nmtoken** [metadata101/iso19139.gemini23#8]
File identifier: 7928d609-e225-494c-ab79-99b92de8b5bb

    <gmd:hierarchyLevel xmlns:geonet="http://www.fao.org/geonetwork">
          <gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"
                            codeListValue="series"/>
    </gmd:hierarchyLevel>

Fails GEMINI 2.3 schematron validation (run in oXygen)

> System ID: C:\Testing\AstunDev\GEM23-METADATA\7928d609-e225-494c-ab79-99b92de8b5bb.xml
Main validation file: C:\Testing\AstunDev\GEM23-METADATA\7928d609-e225-494c-ab79-99b92de8b5bb.xml
Scenario name: GEMINI23
Engine name: ISO Schematron
Severity: error
Description: MI-41a (Conformity): There must be at least one gmd:DQ_ConformanceResult
Start location: 13:0

and

> System ID: C:\Testing\AstunDev\GEM23-METADATA\7928d609-e225-494c-ab79-99b92de8b5bb.xml
Main validation file: C:\Testing\AstunDev\GEM23-METADATA\7928d609-e225-494c-ab79-99b92de8b5bb.xml
Scenario name: GEMINI23
Engine name: ISO Schematron
Severity: error
Description: MI-41o (Conformity): Datasets and series must provide a conformance report to [1089/2010]. The INSPIRE rule tells us this must be the EXACT title of the regulation, which is: Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services
Start location: 322:0

Currently have:

      <gmd:dataQualityInfo xmlns:geonet="http://www.fao.org/geonetwork">
          <gmd:DQ_DataQuality>
             <gmd:scope>
                <gmd:DQ_Scope>
                   <gmd:level>
                      <gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"
                                        codeListValue="series"/>
                   </gmd:level>
                </gmd:DQ_Scope>
             </gmd:scope>
             <gmd:lineage>
                <gmd:LI_Lineage>
                   <gmd:statement>
                      <gco:CharacterString>Unknown</gco:CharacterString>
                   </gmd:statement>
                </gmd:LI_Lineage>
             </gmd:lineage>
          </gmd:DQ_DataQuality>
      </gmd:dataQualityInfo>

but require at least:

      <gmd:dataQualityInfo xmlns:geonet="http://www.fao.org/geonetwork">
          <gmd:DQ_DataQuality>
             <gmd:scope>
                <gmd:DQ_Scope>
                   <gmd:level>
                      <gmd:MD_ScopeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"
                                        codeListValue="series"/>
                   </gmd:level>
                </gmd:DQ_Scope>
             </gmd:scope>
             <gmd:report>
                <gmd:DQ_DomainConsistency>
                   <gmd:result>
                      <gmd:DQ_ConformanceResult>
                         <gmd:specification>
                            <gmd:CI_Citation>
                               <gmd:title>
                                  <gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2010/1089">Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services</gmx:Anchor>
                               </gmd:title>
                               <gmd:date>
                                  <gmd:CI_Date>
                                     <gmd:date>
                                        <gco:Date>2010-12-08</gco:Date>
                                     </gmd:date>
                                     <gmd:dateType>
                                        <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode"
                                           codeListValue="publication"/>
                                     </gmd:dateType>
                                  </gmd:CI_Date>
                               </gmd:date>
                            </gmd:CI_Citation>
                         </gmd:specification>
                         <gmd:explanation gco:nilReason="missing" />
                         <gmd:pass gco:nilReason="unknown"/>
                      </gmd:DQ_ConformanceResult>
                   </gmd:result>
                </gmd:DQ_DomainConsistency>
             </gmd:report>
             <gmd:lineage>
                <gmd:LI_Lineage>
                   <gmd:statement>
                      <gco:CharacterString>Unknown</gco:CharacterString>
                   </gmd:statement>
                </gmd:LI_Lineage>
             </gmd:lineage>
          </gmd:DQ_DataQuality>
      </gmd:dataQualityInfo>

**Comment by archaeogeek** [comment]
Yep, that's an example record from the official AGI Guidance https://www.agi.org.uk/40-gemini/1043-series-metadata-example-old so we'll need to raise it with them

**Comment by nmtoken** [comment]
Perhaps the 'old' in the URL is a clue that it's not current, is there a direct link to it from one of the GEMINI 2.3 pages?

I don't recall a series metadata example in the bundled examples for GEMINI 2.3

**Comment by archaeogeek** [comment]
It's linked from https://www.agi.org.uk/40-gemini/1048-uk-gemini-encoding-guidance. I've reported it, and yes the problem is that there is no bundled example, hence why I used this one :-)
